### ISSUE TITLE
Not sure where one of the constants is coming from

### ISSUE THREAD

**Issue by lawliet3738** [OndrejMarsalek/Fourier-DVR-1D#1]
https://github.com/OndrejMarsalek/Fourier-DVR-1D/blob/f818b348ac3aa84735c597ce76ad1a184279acee/fourier_DVR_1D/fourier_DVR_1D.py#L60

I wonder where this "fact" constant is coming from? Why is it exactly -8.0 * (b-a) / np.pi**2?

Thanks!

**Comment by OndrejMarsalek** [comment]
Look at Appendix 2 of the reference cited in the class doc string:

https://aip.scitation.org/doi/10.1063/1.471593
